<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sair</name>
   <tag></tag>
   <elementGuidId>e1bfe323-0859-4633-bb3f-ed54fd2092ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'executarLogout()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;executarLogout\(\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Sair&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d950a354-91a5-4eea-9cc1-0e92413b7575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>executarLogout()</value>
      <webElementGuid>36a2d190-0714-4927-8f3b-606794b4d224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sair</value>
      <webElementGuid>13958b42-7a59-4c55-be30-4fdb7788909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-77cb1e12c81978749d27b8f1960c12c8</value>
      <webElementGuid>47c7cd18-e8cb-4ede-a075-38f33f86e9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'executarLogout()']</value>
      <webElementGuid>754715b9-4c37-4fc2-9012-95526eb21833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'executarLogout()']</value>
      <webElementGuid>67fce893-0105-4c29-8fb1-72fbbffc332e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Sair' or . = ' Sair')]</value>
      <webElementGuid>b8465768-147a-4a9a-bed9-cdc1c76c6b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
