<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Adicionar Animal</name>
   <tag></tag>
   <elementGuidId>581e898d-4477-44e4-a8e5-b230d04fe276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'mudarSubTela('registar-animal')']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;mudarSubTela\(\'registar-animal\'\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;+ Adicionar Animal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>584af7e6-835b-4299-9430-06401a1a30ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary</value>
      <webElementGuid>6e247e13-8975-4d3c-b8d0-7c1d5424669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mudarSubTela('registar-animal')</value>
      <webElementGuid>0b8c76c3-c431-4ccf-addb-9be5aef40b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Adicionar Animal</value>
      <webElementGuid>53da5884-b4cd-4757-bfba-92c7b38401cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6bbe40d06242be56e770412fd44afbcb</value>
      <webElementGuid>05f3923a-3880-43ef-847c-aea15debdba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'mudarSubTela('registar-animal')']</value>
      <webElementGuid>e1666767-6036-466a-a7c1-ac3173e7aeb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'mudarSubTela('registar-animal')']</value>
      <webElementGuid>cebe4318-5006-42ac-866c-5d6a7335988e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '+ Adicionar Animal' or . = '+ Adicionar Animal')]</value>
      <webElementGuid>64e9eb6c-cee9-437f-a8c3-c0049145b4e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
