<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_18_00</name>
   <tag></tag>
   <elementGuidId>ac81ea29-1e44-4f8a-b214-f7eda9b57e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@data-livre = 'true') and (position() = 14)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-livre=&quot;true&quot;]:nth-child(14)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;18:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bac86457-5678-4447-acc4-5296150fcfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slot-card</value>
      <webElementGuid>9a8e4072-1e95-43c8-818f-a0c3bcd4de89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-livre</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecf5341f-8bc1-4adf-90ae-3f8129318793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hora</name>
      <type>Main</type>
      <value>18:00</value>
      <webElementGuid>63d6dd35-78f7-4e11-8ca6-213b1209bb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>18:00</value>
      <webElementGuid>5d48aea3-73d8-40bb-ac10-4228d4555221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f7c999a84067319b6d8be224486555ff</value>
      <webElementGuid>dfb5cf6c-7381-431a-b73f-0224944ae30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@data-livre = 'true') and (position() = 14)]</value>
      <webElementGuid>fe50fe08-683f-433d-b924-52159511b392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@data-livre = 'true') and (position() = 14)]</value>
      <webElementGuid>db80301c-3573-475d-a46d-b02dadd8c436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '18:00' or . = '18:00')]</value>
      <webElementGuid>a8ee4d7f-6f7d-4e43-a0b2-9967d42b716b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
