<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_marcar-data-input</name>
   <tag></tag>
   <elementGuidId>d1a106bb-f1a7-44cb-96f1-c7fcb4e38e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'marcar-data-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#marcar-data-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#marcar-data-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83496c1b-8648-445d-b623-1e3c55479a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>aacafffc-88d7-4515-81a3-bc480eebc89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marcar-data-input</value>
      <webElementGuid>8656ea20-d376-413d-83cd-79a391cf4dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gerarHorariosCalendario()</value>
      <webElementGuid>cf191c2f-b0a0-4495-ad5d-1b4992df26b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2026-05-29</value>
      <webElementGuid>5508c347-06b3-43fc-b759-a7ec623bf767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e9a71ce17d9c30f80d40eb0294bb1fe6</value>
      <webElementGuid>d35e2efd-16e7-434b-9a1a-38b9bf5d1f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'marcar-data-input']</value>
      <webElementGuid>ba1a1c74-19e1-4ab0-ac53-96e64dcf5e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'marcar-data-input']</value>
      <webElementGuid>0c010224-b9e2-4a2a-85c8-9f48baf17073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'marcar-data-input']</value>
      <webElementGuid>7bf5c031-c392-44a4-88c1-5ef118a5fc29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
