<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_245678901</name>
   <tag></tag>
   <elementGuidId>27cebdab-7470-44e3-b0ea-8dba951b7ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'reg-nif']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel' and @id = 'reg-nif' and @placeholder = '245678901']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reg-nif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;245678901&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e47e2c4-f100-4df8-ad25-907189564e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>79585d62-84c9-4666-9d3c-56120e3d0c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-nif</value>
      <webElementGuid>32b352cb-24de-48ab-8d4c-f21167ad2397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>245678901</value>
      <webElementGuid>d59900d5-cb73-4a89-9bc6-d73d4b9026d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>d47f1570-5e1e-42ee-aef8-d9d9b94f4633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>cc72b94a-1a11-4dd3-8530-f6e25b200b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>fbab426c-8e67-4202-ab4b-a4d53b2ae5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/\D/g,'')</value>
      <webElementGuid>2d7326ae-f0ad-40b0-b543-e457ab036858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fb37588ec69b6fa05bf56a829f022561</value>
      <webElementGuid>c8d1cb46-2e37-4771-86b1-650fc4be81f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'reg-nif']</value>
      <webElementGuid>7b9b7c0d-8d60-4630-9fc5-95b484da51da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'reg-nif']</value>
      <webElementGuid>a996f9ca-b4c3-4ca6-a109-753bbfa66804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'reg-nif' and @placeholder = '245678901']</value>
      <webElementGuid>302302c2-e053-485a-a37c-24f7d4fc0adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
