<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_animal-especie-input</name>
   <tag></tag>
   <elementGuidId>8be09b4a-fd61-41a7-8305-90d84eb45cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'animal-especie-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#animal-especie-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#animal-especie-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ca379b8-e23d-48a2-b294-e8a5e1b0df77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>animal-especie-input</value>
      <webElementGuid>2c4f67c1-e968-4343-ba9b-cb14ad51fef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>atualizarOpcoesRacas()</value>
      <webElementGuid>ff09eeef-8330-487b-9bc3-6a1d4a4fb960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Selecione...
                                Cão
                                Gato
                                Furão
                            </value>
      <webElementGuid>9ec76b81-d820-409b-9efa-87a65e13c024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7eb9b572833a6cffc1168d70e48d874b</value>
      <webElementGuid>86aa3c12-708a-4b55-8150-5b7b1795d7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'animal-especie-input']</value>
      <webElementGuid>c1517922-877c-4a15-9304-70aeaf4732e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'animal-especie-input']</value>
      <webElementGuid>cc5b4ffd-01ca-4aa1-a10e-e68b88b19686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'animal-especie-input' and (text() = '
                                Selecione...
                                Cão
                                Gato
                                Furão
                            ' or . = '
                                Selecione...
                                Cão
                                Gato
                                Furão
                            ')]</value>
      <webElementGuid>5b78ea86-5703-4abc-a76b-62e6804008d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
